<?php 
// if( function_exists('acf_add_local_field_group') ):

//     acf_add_local_field_group(array(
//         'key' => 'group_5db057090a35d',
//         'title' => 'Danh sách câu hỏi',
//         'fields' => array(
//             array(
//                 'key' => 'field_5db057b2b517b',
//                 'label' => 'Danh sách câu hỏi ( List questions )',
//                 'name' => 'list_question',
//                 'type' => 'repeater',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'collapsed' => '',
//                 'min' => 0,
//                 'max' => 0,
//                 'layout' => 'table',
//                 'button_label' => '',
//                 'sub_fields' => array(
//                     array(
//                         'key' => 'field_5db057d0b517c',
//                         'label' => 'Tiêu đề câu hỏi ( title )',
//                         'name' => 'title',
//                         'type' => 'text',
//                         'instructions' => '',
//                         'required' => 0,
//                         'conditional_logic' => 0,
//                         'wrapper' => array(
//                             'width' => '30',
//                             'class' => '',
//                             'id' => '',
//                         ),
//                         'default_value' => '',
//                         'placeholder' => '',
//                         'prepend' => '',
//                         'append' => '',
//                         'maxlength' => '',
//                     ),
//                     array(
//                         'key' => 'field_5db057fcb517d',
//                         'label' => 'Câu trả lời câu hỏi ( title )',
//                         'name' => 'content',
//                         'type' => 'textarea',
//                         'instructions' => '',
//                         'required' => 0,
//                         'conditional_logic' => 0,
//                         'wrapper' => array(
//                             'width' => '70',
//                             'class' => '',
//                             'id' => '',
//                         ),
//                         'default_value' => '',
//                         'placeholder' => '',
//                         'maxlength' => '',
//                         'rows' => 4,
//                         'new_lines' => '',
//                     ),
//                 ),
//             ),
//         ),
//         'location' => array(
//             array(
//                 array(
//                     'param' => 'page',
//                     'operator' => '==',
//                     'value' => '127',
//                 ),
//             ),
//         ),
//         'menu_order' => 0,
//         'position' => 'normal',
//         'style' => 'default',
//         'label_placement' => 'top',
//         'instruction_placement' => 'label',
//         'hide_on_screen' => '',
//         'active' => true,
//         'description' => '',
//     ));
    
//     acf_add_local_field_group(array(
//         'key' => 'group_5d9e97fb492bb',
//         'title' => 'Home - banner',
//         'fields' => array(
//             array(
//                 'key' => 'field_5d9e9ae044bd2',
//                 'label' => 'Home Banner',
//                 'name' => 'home_banner',
//                 'type' => 'flexible_content',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'layouts' => array(
//                     'layout_5d9e9db8e08d5' => array(
//                         'key' => 'layout_5d9e9db8e08d5',
//                         'name' => 'them_1_banner',
//                         'label' => 'Thêm 1 banner',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5d9e9b7244bd3',
//                                 'label' => 'title',
//                                 'name' => 'title',
//                                 'type' => 'text',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '30',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'prepend' => '',
//                                 'append' => '',
//                                 'maxlength' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d9e9b8f44bd4',
//                                 'label' => 'content',
//                                 'name' => 'content',
//                                 'type' => 'textarea',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '70',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'maxlength' => '',
//                                 'rows' => 4,
//                                 'new_lines' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d9e9b9b44bd5',
//                                 'label' => 'image',
//                                 'name' => 'image',
//                                 'type' => 'image',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '50',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'return_format' => 'array',
//                                 'preview_size' => 'medium',
//                                 'library' => 'all',
//                                 'min_width' => '',
//                                 'min_height' => '',
//                                 'min_size' => '',
//                                 'max_width' => '',
//                                 'max_height' => '',
//                                 'max_size' => '',
//                                 'mime_types' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d9e9cb645f10',
//                                 'label' => 'link',
//                                 'name' => 'link',
//                                 'type' => 'text',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '50',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'prepend' => '',
//                                 'append' => '',
//                                 'maxlength' => '',
//                             ),
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//                 ),
//                 'button_label' => 'Add Row',
//                 'min' => '',
//                 'max' => '',
//             ),
//         ),
//         'location' => array(
//             array(
//                 array(
//                     'param' => 'page',
//                     'operator' => '==',
//                     'value' => '9',
//                 ),
//             ),
//         ),
//         'menu_order' => 0,
//         'position' => 'normal',
//         'style' => 'default',
//         'label_placement' => 'top',
//         'instruction_placement' => 'label',
//         'hide_on_screen' => '',
//         'active' => true,
//         'description' => '',
//     ));
    
//     acf_add_local_field_group(array(
//         'key' => 'group_5d9ecfc415806',
//         'title' => 'Home - How It Works',
//         'fields' => array(
//             array(
//                 'key' => 'field_5d9ed0d31fa75',
//                 'label' => 'Big title',
//                 'name' => 'how_work_big_title',
//                 'type' => 'text',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '100',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'maxlength' => '',
//             ),
//             array(
//                 'key' => 'field_5da5dbdc810d6',
//                 'label' => 'Content',
//                 'name' => 'how_work_content',
//                 'type' => 'textarea',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '100',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'maxlength' => '',
//                 'rows' => 4,
//                 'new_lines' => '',
//             ),
//             array(
//                 'key' => 'field_5d9ed0171fa71',
//                 'label' => 'Items',
//                 'name' => 'how_work_items',
//                 'type' => 'flexible_content',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'layouts' => array(
//                     'layout_5d9ed10eb98b0' => array(
//                         'key' => 'layout_5d9ed10eb98b0',
//                         'name' => 'them',
//                         'label' => 'Thêm',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5d9ed11d89fe3',
//                                 'label' => 'Title',
//                                 'name' => 'title',
//                                 'type' => 'text',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '50',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'prepend' => '',
//                                 'append' => '',
//                                 'maxlength' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d9ed13f89fe5',
//                                 'label' => 'Image',
//                                 'name' => 'image',
//                                 'type' => 'image',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '50',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'return_format' => 'array',
//                                 'preview_size' => 'medium',
//                                 'library' => 'all',
//                                 'min_width' => '',
//                                 'min_height' => '',
//                                 'min_size' => '',
//                                 'max_width' => '',
//                                 'max_height' => '',
//                                 'max_size' => '',
//                                 'mime_types' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d9ed13389fe4',
//                                 'label' => 'Content',
//                                 'name' => 'content',
//                                 'type' => 'text',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'prepend' => '',
//                                 'append' => '',
//                                 'maxlength' => '',
//                             ),
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//                 ),
//                 'button_label' => 'Add Row',
//                 'min' => '',
//                 'max' => '',
//             ),
//         ),
//         'location' => array(
//             array(
//                 array(
//                     'param' => 'page',
//                     'operator' => '==',
//                     'value' => '9',
//                 ),
//             ),
//         ),
//         'menu_order' => 0,
//         'position' => 'normal',
//         'style' => 'default',
//         'label_placement' => 'top',
//         'instruction_placement' => 'label',
//         'hide_on_screen' => '',
//         'active' => true,
//         'description' => '',
//     ));
    
//     acf_add_local_field_group(array(
//         'key' => 'group_5d9fa548df147',
//         'title' => 'Home - Key To Success',
//         'fields' => array(
//             array(
//                 'key' => 'field_5d9fa54b0ad6f',
//                 'label' => 'items',
//                 'name' => 'key_to_success',
//                 'type' => 'flexible_content',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'layouts' => array(
//                     'layout_5d9fa5506849c' => array(
//                         'key' => 'layout_5d9fa5506849c',
//                         'name' => 'add_items',
//                         'label' => 'Thêm mới',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5d9fa5770ad70',
//                                 'label' => 'title',
//                                 'name' => 'title',
//                                 'type' => 'text',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '30',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'prepend' => '',
//                                 'append' => '',
//                                 'maxlength' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d9fa5830ad71',
//                                 'label' => 'icon ( dashicon )',
//                                 'name' => 'dashicon',
//                                 'type' => 'image',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '30',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'return_format' => 'array',
//                                 'preview_size' => 'medium',
//                                 'library' => 'all',
//                                 'min_width' => '',
//                                 'min_height' => '',
//                                 'min_size' => '',
//                                 'max_width' => '',
//                                 'max_height' => '',
//                                 'max_size' => '',
//                                 'mime_types' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d9fa5990ad72',
//                                 'label' => 'number',
//                                 'name' => 'number',
//                                 'type' => 'text',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'prepend' => '',
//                                 'append' => '',
//                                 'maxlength' => '',
//                             ),
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//                 ),
//                 'button_label' => 'Add Row',
//                 'min' => '',
//                 'max' => '',
//             ),
//         ),
//         'location' => array(
//             array(
//                 array(
//                     'param' => 'page',
//                     'operator' => '==',
//                     'value' => '9',
//                 ),
//             ),
//         ),
//         'menu_order' => 0,
//         'position' => 'normal',
//         'style' => 'default',
//         'label_placement' => 'top',
//         'instruction_placement' => 'label',
//         'hide_on_screen' => '',
//         'active' => true,
//         'description' => '',
//     ));
    
//     acf_add_local_field_group(array(
//         'key' => 'group_5da5dea7500b4',
//         'title' => 'Home - Khách hàng của chúng tôi ( Our Clients )',
//         'fields' => array(
//             array(
//                 'key' => 'field_5da5ecd90aecb',
//                 'label' => 'Tiêu Đề',
//                 'name' => 'home_our_clients_title',
//                 'type' => 'text',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '40',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'maxlength' => '',
//             ),
//             array(
//                 'key' => 'field_5da5ecf50aecc',
//                 'label' => 'Nội Dung',
//                 'name' => 'home_our_clients_content',
//                 'type' => 'textarea',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '60',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'maxlength' => '',
//                 'rows' => 4,
//                 'new_lines' => '',
//             ),
//             array(
//                 'key' => 'field_5da5dea7556a5',
//                 'label' => 'Danh sách khách hàng ( list )',
//                 'name' => 'home_our_clients',
//                 'type' => 'flexible_content',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'layouts' => array(
//                     'layout_5d9fa5506849c' => array(
//                         'key' => 'layout_5d9fa5506849c',
//                         'name' => 'add_items',
//                         'label' => 'Thêm mới',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5da5dea7575e6',
//                                 'label' => 'Tên khách hàng ( title )',
//                                 'name' => 'title',
//                                 'type' => 'text',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '50',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'prepend' => '',
//                                 'append' => '',
//                                 'maxlength' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5da5dea7579ce',
//                                 'label' => 'Logo',
//                                 'name' => 'image',
//                                 'type' => 'image',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '50',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'return_format' => 'array',
//                                 'preview_size' => 'medium',
//                                 'library' => 'all',
//                                 'min_width' => '',
//                                 'min_height' => '',
//                                 'min_size' => '',
//                                 'max_width' => '',
//                                 'max_height' => '',
//                                 'max_size' => '',
//                                 'mime_types' => '',
//                             ),
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//                 ),
//                 'button_label' => 'Add Row',
//                 'min' => '',
//                 'max' => '',
//             ),
//         ),
//         'location' => array(
//             array(
//                 array(
//                     'param' => 'page',
//                     'operator' => '==',
//                     'value' => '9',
//                 ),
//             ),
//         ),
//         'menu_order' => 0,
//         'position' => 'normal',
//         'style' => 'default',
//         'label_placement' => 'top',
//         'instruction_placement' => 'label',
//         'hide_on_screen' => '',
//         'active' => true,
//         'description' => '',
//     ));
    
//     acf_add_local_field_group(array(
//         'key' => 'group_5d9ed31299322',
//         'title' => 'Home - Khu vực hoạt đông( Practice Area )',
//         'fields' => array(
//             array(
//                 'key' => 'field_5d9ed312a3734',
//                 'label' => 'Tiêu đề',
//                 'name' => 'practice_big_title',
//                 'type' => 'text',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '100',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'maxlength' => '',
//             ),
//             array(
//                 'key' => 'field_5d9ed312a3b1c',
//                 'label' => 'items',
//                 'name' => 'practice_items',
//                 'type' => 'flexible_content',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'layouts' => array(
//                     'layout_5d9ed10eb98b0' => array(
//                         'key' => 'layout_5d9ed10eb98b0',
//                         'name' => 'them',
//                         'label' => 'Thêm',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5d9ed312a799d',
//                                 'label' => 'Title',
//                                 'name' => 'title',
//                                 'type' => 'text',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '35',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'prepend' => '',
//                                 'append' => '',
//                                 'maxlength' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d9ed312a816d',
//                                 'label' => 'Content',
//                                 'name' => 'content',
//                                 'type' => 'textarea',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '65',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'maxlength' => '',
//                                 'rows' => 4,
//                                 'new_lines' => '',
//                             ),
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//                 ),
//                 'button_label' => 'Add Row',
//                 'min' => '',
//                 'max' => '',
//             ),
//         ),
//         'location' => array(
//             array(
//                 array(
//                     'param' => 'page',
//                     'operator' => '==',
//                     'value' => '9',
//                 ),
//             ),
//         ),
//         'menu_order' => 0,
//         'position' => 'normal',
//         'style' => 'default',
//         'label_placement' => 'top',
//         'instruction_placement' => 'label',
//         'hide_on_screen' => '',
//         'active' => true,
//         'description' => '',
//     ));
    
//     acf_add_local_field_group(array(
//         'key' => 'group_5d9eb8be2cf08',
//         'title' => 'Home - Tư vấn ( consultation )',
//         'fields' => array(
//             array(
//                 'key' => 'field_5d9eb8c210f3d',
//                 'label' => 'Tư vấn ( consultation )',
//                 'name' => 'home_consultation',
//                 'type' => 'group',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'layout' => 'block',
//                 'sub_fields' => array(
//                     array(
//                         'key' => 'field_5d9eb8fd10f3e',
//                         'label' => 'text',
//                         'name' => 'text',
//                         'type' => 'textarea',
//                         'instructions' => '',
//                         'required' => 0,
//                         'conditional_logic' => 0,
//                         'wrapper' => array(
//                             'width' => '80',
//                             'class' => '',
//                             'id' => '',
//                         ),
//                         'default_value' => '',
//                         'placeholder' => '',
//                         'maxlength' => '',
//                         'rows' => '',
//                         'new_lines' => '',
//                     ),
//                     array(
//                         'key' => 'field_5d9eb91810f3f',
//                         'label' => 'Title Button',
//                         'name' => 'title_button',
//                         'type' => 'text',
//                         'instructions' => '',
//                         'required' => 0,
//                         'conditional_logic' => 0,
//                         'wrapper' => array(
//                             'width' => '20',
//                             'class' => '',
//                             'id' => '',
//                         ),
//                         'default_value' => '',
//                         'placeholder' => '',
//                         'prepend' => '',
//                         'append' => '',
//                         'maxlength' => '',
//                     ),
//                 ),
//             ),
//         ),
//         'location' => array(
//             array(
//                 array(
//                     'param' => 'page',
//                     'operator' => '==',
//                     'value' => '9',
//                 ),
//             ),
//         ),
//         'menu_order' => 0,
//         'position' => 'normal',
//         'style' => 'default',
//         'label_placement' => 'top',
//         'instruction_placement' => 'label',
//         'hide_on_screen' => '',
//         'active' => true,
//         'description' => '',
//     ));
    
//     acf_add_local_field_group(array(
//         'key' => 'group_5d9eec1ea70ce',
//         'title' => 'Home - Về Chúng tôi ( Why Choose Us )',
//         'fields' => array(
//             array(
//                 'key' => 'field_5da4b9ece577e',
//                 'label' => 'Tiêu Đề ( Title )',
//                 'name' => 'about_us_title',
//                 'type' => 'text',
//                 'instructions' => 'Bạn đặt dòng chữ vàng trong Ngặc {{	}}.<br>
//     Ví Dụ: {{ Chữ vàng }} Chữ Thường',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '50',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'maxlength' => '',
//             ),
//             array(
//                 'key' => 'field_5da4bafae577f',
//                 'label' => 'Nội Dung ( Content )',
//                 'name' => 'about_us_content',
//                 'type' => 'textarea',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '50',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'maxlength' => '',
//                 'rows' => 4,
//                 'new_lines' => '',
//             ),
//             array(
//                 'key' => 'field_5d9eec28c0bd7',
//                 'label' => 'items',
//                 'name' => 'about_us_items',
//                 'type' => 'flexible_content',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'layouts' => array(
//                     'layout_5d9eec480e8d5' => array(
//                         'key' => 'layout_5d9eec480e8d5',
//                         'name' => 'how_work_them',
//                         'label' => 'Thêm',
//                         'display' => 'block',
//                         'sub_fields' => array(
//                             array(
//                                 'key' => 'field_5d9eec52c0bd8',
//                                 'label' => 'Title',
//                                 'name' => 'title',
//                                 'type' => 'text',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '30',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'prepend' => '',
//                                 'append' => '',
//                                 'maxlength' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d9eec6dc0bd9',
//                                 'label' => 'content',
//                                 'name' => 'content',
//                                 'type' => 'text',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '30',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'default_value' => '',
//                                 'placeholder' => '',
//                                 'prepend' => '',
//                                 'append' => '',
//                                 'maxlength' => '',
//                             ),
//                             array(
//                                 'key' => 'field_5d9eec7ac0bda',
//                                 'label' => 'image',
//                                 'name' => 'image',
//                                 'type' => 'image',
//                                 'instructions' => '',
//                                 'required' => 0,
//                                 'conditional_logic' => 0,
//                                 'wrapper' => array(
//                                     'width' => '40',
//                                     'class' => '',
//                                     'id' => '',
//                                 ),
//                                 'return_format' => 'array',
//                                 'preview_size' => 'medium',
//                                 'library' => 'all',
//                                 'min_width' => '',
//                                 'min_height' => '',
//                                 'min_size' => '',
//                                 'max_width' => '',
//                                 'max_height' => '',
//                                 'max_size' => '',
//                                 'mime_types' => '',
//                             ),
//                         ),
//                         'min' => '',
//                         'max' => '',
//                     ),
//                 ),
//                 'button_label' => 'Add Row',
//                 'min' => '',
//                 'max' => '',
//             ),
//         ),
//         'location' => array(
//             array(
//                 array(
//                     'param' => 'page',
//                     'operator' => '==',
//                     'value' => '9',
//                 ),
//             ),
//         ),
//         'menu_order' => 0,
//         'position' => 'normal',
//         'style' => 'default',
//         'label_placement' => 'top',
//         'instruction_placement' => 'label',
//         'hide_on_screen' => '',
//         'active' => true,
//         'description' => '',
//     ));
    
//     acf_add_local_field_group(array(
//         'key' => 'group_5daf55a18ce2a',
//         'title' => 'Icon dịch vụ',
//         'fields' => array(
//             array(
//                 'key' => 'field_5daf55c047260',
//                 'label' => 'Icon Dịch vụ',
//                 'name' => 'post_services',
//                 'type' => 'image',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'return_format' => 'array',
//                 'preview_size' => 'medium',
//                 'library' => 'all',
//                 'min_width' => '',
//                 'min_height' => '',
//                 'min_size' => '',
//                 'max_width' => '',
//                 'max_height' => '',
//                 'max_size' => '',
//                 'mime_types' => '',
//             ),
//         ),
//         'location' => array(
//             array(
//                 array(
//                     'param' => 'post_category',
//                     'operator' => '==',
//                     'value' => 'category:dich-vu',
//                 ),
//             ),
//         ),
//         'menu_order' => 0,
//         'position' => 'normal',
//         'style' => 'default',
//         'label_placement' => 'top',
//         'instruction_placement' => 'label',
//         'hide_on_screen' => '',
//         'active' => true,
//         'description' => '',
//     ));
    
//     acf_add_local_field_group(array(
//         'key' => 'group_5db0d32072b6c',
//         'title' => 'Thông tin liên hệ',
//         'fields' => array(
//             array(
//                 'key' => 'field_5db0d33707680',
//                 'label' => 'Địa chỉ ( số nhà )',
//                 'name' => 'contact_addres_1',
//                 'type' => 'text',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '50',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'maxlength' => '',
//             ),
//             array(
//                 'key' => 'field_5db0d3be07681',
//                 'label' => 'Địa chỉ ( Thành phố, quốc gia )',
//                 'name' => 'contact_addres_2',
//                 'type' => 'text',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '50',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'maxlength' => '',
//             ),
//             array(
//                 'key' => 'field_5db0d3e007682',
//                 'label' => 'Số điện thoại',
//                 'name' => 'contact_phone',
//                 'type' => 'text',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '50',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'maxlength' => '',
//             ),
//             array(
//                 'key' => 'field_5db0d3f907683',
//                 'label' => 'Email',
//                 'name' => 'contact_mail',
//                 'type' => 'text',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '50',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'maxlength' => '',
//             ),
//             array(
//                 'key' => 'field_5db0d40807684',
//                 'label' => 'Thời gian làm việc ( theo giờ )',
//                 'name' => 'contact_time_1',
//                 'type' => 'text',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '50',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => 'Từ 7h đến 17h30',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'maxlength' => '',
//             ),
//             array(
//                 'key' => 'field_5db0d43b07685',
//                 'label' => 'Thời gian làm việc ( theo ngày )',
//                 'name' => 'contact_time_2',
//                 'type' => 'text',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '50',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => 'từ thứ 2 đến thứ 6',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'maxlength' => '',
//             ),
//             array(
//                 'key' => 'field_5db0d4a64d73c',
//                 'label' => 'Google map',
//                 'name' => 'google_map',
//                 'type' => 'textarea',
//                 'instructions' => 'Vào google map tìm vị trí của địa điểm muốn tìm, lấy sẻ trong thẻ iframe',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3723.4505477375733!2d105.73326931424575!3d21.05465999227104!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31345457e292d5bf%3A0x20ac91c94d74439a!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBDw7RuZyBuZ2hp4buHcCBIw6AgTuG7mWk!5e0!3m2!1svi!2sus!4v1571871748369!5m2!1svi!2sus',
//                 'placeholder' => '',
//                 'maxlength' => '',
//                 'rows' => 4,
//                 'new_lines' => '',
//             ),
//         ),
//         'location' => array(
//             array(
//                 array(
//                     'param' => 'options_page',
//                     'operator' => '==',
//                     'value' => 'acf-options-lien-he',
//                 ),
//             ),
//         ),
//         'menu_order' => 0,
//         'position' => 'normal',
//         'style' => 'default',
//         'label_placement' => 'top',
//         'instruction_placement' => 'label',
//         'hide_on_screen' => '',
//         'active' => true,
//         'description' => '',
//     ));
    
//     endif;